# Generated by Django 5.2.17 on 2026-09-22 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('paid_at', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-paid_at', 'reference'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'EUR'])), name='payment_currency_supported')],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_decided', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_request', to='refunds.payment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('from_status', models.CharField(blank=True, max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_events', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='refunds.refundrequest')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'EUR'])), name='refund_currency_supported'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='refund_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('decision_reason', ''), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ['approved', 'rejected']), models.Q(('decision_reason', ''), _negated=True)), _connector='OR'), name='refund_decision_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='refundrequest',
            constraint=models.CheckConstraint(condition=models.Q(('decided_by__isnull', True), models.Q(('decided_by', models.F('requested_by')), _negated=True), _connector='OR'), name='refund_no_self_decision'),
        ),
    ]
