# Generated by Django 5.2.17 on 2026-09-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('waiting_on_customer', 'Waiting on customer'), ('escalated', 'Escalated'), ('closed', 'Closed')], max_length=25)),
                ('assigned_reviewer', models.CharField(blank=True, max_length=80)),
                ('opened_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-opened_at', 'case_id'],
            },
        ),
    ]
